### ISSUE TITLE
Undefined Reference when Compiling and Linking

### ISSUE THREAD

**Issue by baker12** [rlamarche/camera-toolbox#1]
![error](https://cloud.githubusercontent.com/assets/10013663/21470369/647cbd90-ca4b-11e6-9b4d-01f5f31b90c6.png)
When compiling I get a link error that appears to be with the gphoto libraries in gpcamera.cpp If I'm doing something wrong or need more info let me know. I should have all of the libraries installed

-AB

**Comment by rlamarche** [comment]
Hi, are you in sync with the git repo ?
Have you builded libgphoto2 yourself or installed it with apt-get ?

I've made some changes in the build files recently and now I prefer to use precompiled or separately compiled version of libgphoto.

Look at these changes about the libs : https://github.com/rlamarche/camera-toolbox/commit/de93e4971b5b3cea1fc0f5de607864280958033a#diff-4edeef19cfe50786e2ef0877dd63be76

It seems that your linker does not find the libgphoto2 libraries.

**Comment by baker12** [comment]
I had libgphoto 2.5.11 already installed on my Pi that I built from their repo. Will this make a difference or do I need to have the built files in the vendor directory?

Edit: Yes I have the latest files from your repo

**Comment by rlamarche** [comment]
Ok I think that the gphoto2 libs are not in your sysroot.
Now that you have installed libgphoto2 on your raspberry pi, you need to re-run the rsync command to populate your sysroot.

Can you list here the steps you did and the order ?

Normaly if you have libgphoto2 in your sysroot you don't need the vendor directory.

**Comment by baker12** [comment]
Found my problem. Didn't realize I also had a much older version installed that got synced to my sysroot so I removed both and reinstalled 2.5.11 and I also had to rsync over my /usr/local folder to my sysroot since the make install put the libraries there and I got it to work! Unfortunately it appears I will need to do some work since I am using a Canon Digital Rebel XT and it errors out trying to open the camera. Thanks for your help!

**Comment by rlamarche** [comment]
Good news !
Ok you have a Canon : I'm very curious to know if it works or why it doesn't work.
There is a GPNikonCamera class. I'm going to create a GPCanonCamera class to support Canon cameras.
Then the correct class would be instanciated here : https://github.com/rlamarche/camera-toolbox/blob/master/app/main.cpp#L174

Can you create a new issue and paste your errors on ?
Thank you very much.

What is exactly your camera model ?
