### ISSUE TITLE
libgphoto2 tree is missing

### ISSUE THREAD

**Issue by claussteinmassl** [rlamarche/camera-toolbox#3]
Hey!

First let me thank you for all your work! This project looks really awesome! :)

Unfortunately I'm having problems to install your toolbox, since your libgphoto2 tree seems to be missing (https://github.com/gphoto/libgphoto2/tree/1783ecdd7f7d52a99fa279e8b1c8dc8b972ad0a2).

Thanks for your help!
cheers,
Claus

**Comment by rlamarche** [comment]
Hi,
Sorry for my late answer.
You can use the master branch of libgphoto2 wihout any problem.
You also can use a precompiled version of libgphoto (by installing it with apt-get for example).

**Comment by claussteinmassl** [comment]
No worries! Thanks for your answer! :)

I thought you had done changes to libgphoto2 itself, which is why I thought I had to use that branch.
I installed the lib via apt-get, but I'm still a bit lost at one point:
Since the vendor/libgphoto2 dir is empty, there is no configure file. But I think, I can't just skip those lines, can I?

> autoreconf --install --symlink
> CFLAGS="--sysroot /path/to/sysroot" PATH="$PATH:/path/to/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/" ./configure --host=arm-linux-gnueabihf

If I do so and try to run qmake I get this error:

> Project ERROR: Unknown module(s) in QT: websockets
> make: *** [sub-app-make_first] Error 3

Please excuse me, if this might be a dumb question. I'm quite new to linux. Thanks very much! :)

**Comment by rlamarche** [comment]
Ok follow the steps here : https://github.com/rlamarche/camera-toolbox#compile
But skip the steps about libgphoto.

You want to build the project for a raspberry pi or your computer ? (desktop)

If for raspberry pi, you need to prepare your cross compile env : https://github.com/rlamarche/camera-toolbox#setup or https://github.com/rlamarche/camera-toolbox-buildroot

If for your desktop computer, install the Qt5 SDK before and use the provided `qmake` to prepare your build :

Note : I've fix the subtree problem, so you can update the git repo.

**Comment by claussteinmassl** [comment]
Thanks!
I'm building for the raspberry pi 3. I've set up a virtual machine on my mac running ubuntu to cross compile and followed all instructions. If I skip the lines about libgphoto and run make (after qmake) I always get this error:

> Project ERROR: Unknown module(s) in QT: websockets
make: *** [sub-app-make_first] Error 3

Any idea how to fix this? I've installed QT as described in the steps before.

PS: I know you've uploaded a precompiled image, but I wanted to install it on my own since I'm also running some other stuff on that same pi which took me quite some time to set them up... :)

**Comment by rlamarche** [comment]
Ok you need to build the qt websockets module.
I've forget to add the steps in the README !

In the folder where the script `deploy.sh` reside :

```
git clone git@github.com:qt/qtwebsockets.git
cd qtwebsockets
../qt5/bin/qmake
make
make install

cd ..
./deploy.sh
```

**Comment by claussteinmassl** [comment]
Ok, next dump question:
Since I got no deploy.sh file I assume I just need to clone this git somewhere in my sysroot?

Thanks for your patience! :)

**Comment by rlamarche** [comment]
in practice you can clone it anywhere you want ;)

**Comment by rlamarche** [comment]
the deploy.sh script is here to push the qt binaries on the raspberry pi :
https://wiki.qt.io/RaspberryPi2EGLFS

The command : `rsync -avz qt5pi pi@IP:/usr/local`

**Comment by claussteinmassl** [comment]
Ok, thanks for that! :)

I think I'm getting closer.... If I now run make I get this error:

> .obj/qwebsocketserver_p.o: In function `QWebSocketServerPrivate::init()':
qwebsocketserver_p.cpp:(.text+0x530): undefined reference to `QSslServer::QSslServer(QObject*)'
qwebsocketserver_p.cpp:(.text+0x900): undefined reference to `QSslServer::newEncryptedConnection()'
qwebsocketserver_p.cpp:(.text+0x90c): undefined reference to `QSslServer::staticMetaObject'
qwebsocketserver_p.cpp:(.text+0x910): undefined reference to `QSslServer::peerVerifyError(QSslError const&)'
qwebsocketserver_p.cpp:(.text+0x91c): undefined reference to `QSslServer::sslErrors(QList<QSslError> const&)'
qwebsocketserver_p.cpp:(.text+0x928): undefined reference to `QSslServer::preSharedKeyAuthenticationRequired(QSslPreSharedKeyAuthenticator*)'
.obj/qwebsocketserver_p.o: In function `QWebSocketServerPrivate::setSslConfiguration(QSslConfiguration const&)':
qwebsocketserver_p.cpp:(.text+0xfd4): undefined reference to `QSslServer::setSslConfiguration(QSslConfiguration const&)'
qwebsocketserver_p.cpp:(.text+0xfdc): undefined reference to `QSslServer::staticMetaObject'
.obj/qwebsocketserver_p.o: In function `QWebSocketServerPrivate::sslConfiguration() const':
qwebsocketserver_p.cpp:(.text+0x1020): undefined reference to `QSslServer::sslConfiguration() const'
qwebsocketserver_p.cpp:(.text+0x1030): undefined reference to `QSslServer::staticMetaObject'
collect2: error: ld returned 1 exit status
make[2]: *** [../../lib/libQt5WebSockets.so.5.10.0] Error 1
make[2]: Leaving directory `/home/parallels/raspi/qt5pi/lib/qtwebsockets/src/websockets'
make[1]: *** [sub-websockets-make_first-ordered] Error 2
make[1]: Leaving directory `/home/parallels/raspi/qt5pi/lib/qtwebsockets/src'
make: *** [sub-src-make_first] Error 2

Is that something I can ignore?

**Comment by rlamarche** [comment]
Have you get the same qt version as the qt version built for the raspberry ?
No you can't go through or you have to disable the websocket server in camera-toolbox.

**Comment by rlamarche** [comment]
I'm talking about the qt version of the qtwebsockets project cloned in git.
I didn't told you to switch to the corresponding branch above.

**Comment by rlamarche** [comment]
`git clone git@github.com:qt/qtwebsockets.git -b 5.6`
or
`git clone git@github.com:qt/qtwebsockets.git -b 5.7`

Make sure you get the corresponding branch.

**Comment by claussteinmassl** [comment]
Thanks very much! Switching the branch resolved that issue! 

Unfortunately I keep getting errors ... :(
Even though I've installed gphoto2 I get this message when running make:

> mainwindow.h:17:36: fatal error: gphoto2/gphoto2-camera.h: No such file or directory
 #include <gphoto2/gphoto2-camera.h>

I've installed gphoto2 via `sudo apt-get install gphoto2`

**Comment by rlamarche** [comment]
Great !
You have to install also headers package :

`sudo apt-get install libgphoto2-dev`

**Comment by claussteinmassl** [comment]
Hmm, I could swear I did exactly that when you told me I could just install the libgphoto master branch. I just installed it again and I think I'm getting closer ... but still not there ... :(
I get a lot of other errors now:

> In file included from gphoto/gpcamera.cpp:19:0:
gphoto/gpcamera.h:73:18: warning: unused parameter ‘captureMode’ [-Wunused-parameter]
     virtual bool setCaptureMode(CaptureMode captureMode) { return false; }
                  ^
gphoto/gpcamera.h:89:18: warning: unused parameter ‘exposurePreview’ [-Wunused-parameter]
     virtual bool setExposurePreview(bool exposurePreview) { return false; }
                  ^
gphoto/gpcamera.h:108:18: warning: unused parameter ‘isoAuto’ [-Wunused-parameter]
     virtual bool setIsoAuto(bool isoAuto) { return false; }
                  ^
gphoto/gpcamera.cpp: In member function ‘virtual bool hpis::GPCamera::capturePhoto()’:
gphoto/gpcamera.cpp:360:21: warning: unused variable ‘camera_file_path’ [-Wunused-variable]
     CameraFilePath *camera_file_path;
                     ^
gphoto/gpcamera.cpp:361:21: warning: unused variable ‘evtype’ [-Wunused-variable]
     CameraEventType evtype;
                     ^
gphoto/gpcamera.cpp:362:11: warning: unused variable ‘data’ [-Wunused-variable]
     void* data;
           ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpGetRangeWidgetInfo(QString, float*, float*, float*)’:
gphoto/gpcamera.cpp:774:101: error: ‘gp_camera_get_single_config’ was not declared in this scope
     ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                     ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpExtractWidgetChoices(QString, QStringList&)’:
gphoto/gpcamera.cpp:796:101: error: ‘gp_camera_get_single_config’ was not declared in this scope
     ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                     ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpSetToggleWidget(QString, int)’:
gphoto/gpcamera.cpp:829:101: error: ‘gp_camera_get_single_config’ was not declared in this scope
     ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                     ^
gphoto/gpcamera.cpp:841:100: error: ‘gp_camera_set_single_config’ was not declared in this scope
     ret = gp_camera_set_single_config(m_camera, widgetName.toStdString().c_str(), widget, m_context);
                                                                                                    ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpSetRangeWidget(QString, float)’:
gphoto/gpcamera.cpp:853:105: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                         ^
gphoto/gpcamera.cpp:867:100: error: ‘gp_camera_set_single_config’ was not declared in this scope
     ret = gp_camera_set_single_config(m_camera, widgetName.toStdString().c_str(), widget, m_context);
                                                                                                    ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpSetRadioWidget(QString, QString)’:
gphoto/gpcamera.cpp:879:105: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                         ^
gphoto/gpcamera.cpp:893:100: error: ‘gp_camera_set_single_config’ was not declared in this scope
     ret = gp_camera_set_single_config(m_camera, widgetName.toStdString().c_str(), widget, m_context);
                                                                                                    ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpSetTextWidget(QString, QString)’:
gphoto/gpcamera.cpp:906:105: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &widget, m_context);
                                                                                                         ^
gphoto/gpcamera.cpp:920:100: error: ‘gp_camera_set_single_config’ was not declared in this scope
     ret = gp_camera_set_single_config(m_camera, widgetName.toStdString().c_str(), widget, m_context);
                                                                                                    ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpGetToggleWidgetValue(QString, int*)’:
gphoto/gpcamera.cpp:932:111: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &cameraWidget, m_context);
                                                                                                               ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpGetRangeWidgetValue(QString, float*)’:
gphoto/gpcamera.cpp:952:111: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &cameraWidget, m_context);
                                                                                                               ^
gphoto/gpcamera.cpp: In member function ‘int hpis::GPCamera::gpGetTextWidgetValue(QString, QString&)’:
gphoto/gpcamera.cpp:967:111: error: ‘gp_camera_get_single_config’ was not declared in this scope
     int ret = gp_camera_get_single_config(m_camera, widgetName.toStdString().c_str(), &cameraWidget, m_context);
                                                                                                               ^
make[1]: *** [gpcamera.o] Error 1
make[1]: Leaving directory `/home/parallels/raspi/camera-toolbox/app'
make: *** [sub-app-make_first] Error 2

**Comment by rlamarche** [comment]
The methods `gp_camera_get_single_config` and `gp_camera_set_single_config` have been added recently (after an issue I opened there https://github.com/gphoto/libgphoto2/issues/78).

So your version of libphoto2 is too old.

Try to do update your packages :

```
sudo apt-get update
sudo apt-get install libgphoto2 libgphoto2-dev
```

**Comment by claussteinmassl** [comment]
Trying to install libgphoto2 via apt-get gives me this error:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgphoto2

So I cloned this git https://github.com/gphoto/libgphoto2.git to my pi, compiled and installed without any problems. 
On my VM running Ubuntu (which I use for cross compiling) I can't configure libgphoto:

> parallels@ubuntu:~/raspi/camera-toolbox/vendor/libgphoto2$ CFLAGS="--sysroot ~/raspi/sysroot" PATH="$PATH:~/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/" ./configure --host=arm-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-gnueabihf-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for POSIX sh $() command substitution... yes
checking for arm-linux-gnueabihf-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for arm-linux-gnueabihf-g++... no
checking for arm-linux-gnueabihf-c++... no
checking for arm-linux-gnueabihf-gpp... no
checking for arm-linux-gnueabihf-aCC... no
checking for arm-linux-gnueabihf-CC... no
checking for arm-linux-gnueabihf-cxx... no
checking for arm-linux-gnueabihf-cc++... no
checking for arm-linux-gnueabihf-cl.exe... no
checking for arm-linux-gnueabihf-FCC... no
checking for arm-linux-gnueabihf-KCC... no
checking for arm-linux-gnueabihf-RCC... no
checking for arm-linux-gnueabihf-xlC_r... no
checking for arm-linux-gnueabihf-xlC... no
checking for g++... g++
configure: WARNING: using cross tools not prefixed with host triplet
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for arm-linux-gnueabihf-ar... no
checking for arm-linux-gnueabihf-lib... no
checking for arm-linux-gnueabihf-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking stdarg.h usability... no
checking stdarg.h presence... yes
configure: WARNING: stdarg.h: present but cannot be compiled
configure: WARNING: stdarg.h:     check for missing prerequisite headers?
configure: WARNING: stdarg.h: see the Autoconf documentation
configure: WARNING: stdarg.h:     section "Present But Cannot Be Compiled"
configure: WARNING: stdarg.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------------- ##
configure: WARNING:     ## Report this to gphoto-devel@lists.sourceforge.net ##
configure: WARNING:     ## ------------------------------------------------- ##
checking for stdarg.h... no
configure: error: 
Building libgphoto2 photo camera library requires <stdarg.h>.

**Comment by rlamarche** [comment]
Run `apt-cache search libgphoto2` on your raspberry and install the good package.
On my computer, it is : `libgphoto2-6` and `libgphoto2-dev`.


if you built libgphoto2 on the rasbperry pi, you can also use the files on it to create your sysroot/cross compile environment :

*From https://wiki.qt.io/RaspberryPi2EGLFS.*

```
mkdir sysroot sysroot/usr sysroot/opt
rsync -avz pi@IP:/lib sysroot
rsync -avz pi@IP:/usr/include sysroot/usr
rsync -avz pi@IP:/usr/lib sysroot/usr
rsync -avz pi@IP:/opt/vc sysroot/opt
```

If you want to crosscompile libgphoto2 on your ubuntu vm, you also need the pi's sysroot.
Then reconfigure libgphoto by running this command : (not sure if it works)

```
autoreconf --install --symlink
CFLAGS="--sysroot /path/to/sysroot" PATH="$PATH:/path/to/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/" ./configure --host=arm-linux-gnueabihf
```

But I don't think this is a good idea.

**Comment by claussteinmassl** [comment]
After running apt-cache search and installing libgphoto2-6 and libgphoto2-dev both on the pi and the Ubuntu VM both told me, that the latest version of each lib was already installed. :/

I followed the instructions on [https://wiki.qt.io/RaspberryPi2EGLFS](url) to setup QT5 with a sysroot on my VM.
After I had build libgphoto2 on the raspberry I rsynced the sysroot back to my vm and fixed symlinks.
I then ran autoreconf and configure with the settings mentioned above and got that error, which I wrote in my previous post.

Don't know what I'm missing right now ... :(

Thank you very much for all your efforts!

**Comment by rlamarche** [comment]
If you have successfuly compiled and installed libgphoto2 on the raspberry
pi, re-sync the sysroot and it will be fine.
Of course, you need to use the qmake of qt5pi, so that it uses the sysroot
of the raspberry pi.

You should not have to build libgphoto2 on your ubuntu vm because you
already build it on the raspberry pi.
Note that if you do this way, you have to uninstall completely libgphoto2-6
+ libgphoto2-dev from the raspberry pi an re-run `sudo make install` on the
libgphoto2 of raspberry pi.

Note that by default if you manually build libgphoto2 (or any project), it
will be installed with the prefix : "/usr/local" instead of "/usr". So when
you sync the sysroot, manually installed libgphoto2 lib and includes are
not downloaded.
So you should re-run the configure script on the raspberry with the prefix
: "/usr".

Do the following on the raspberry pi :

```
sudo apt-get remove libgphoto2-6 libgphoto2-dev
cd /path/to/libbphoto2
make uninstall
./configure --prefix=/usr
make
sudo make install
```
The `make uninstall` is here to cleanup the previous installation.

Then resync the sysroot on your ubunbu vm and try again ;)

**Comment by rlamarche** [comment]
You should not have to build libgphoto2 on your ubuntu vm because you
already build it on the raspberry pi.
Note that if you do this way, you have to uninstall completely libgphoto2-6 and libgphoto2-dev from the raspberry pi an re-run `sudo make install` on the
libgphoto2 of raspberry pi.

Note that by default if you manually build libgphoto2 (or any project), it
will be installed with the prefix : "/usr/local" instead of "/usr". So when
you sync the sysroot, manually installed libgphoto2 lib and includes are
not downloaded.
So you should re-run the configure script on the raspberry with the prefix
: "/usr".

Do the following on the raspberry pi :

```
sudo apt-get remove libgphoto2-6 libgphoto2-dev
cd /path/to/libgphoto2
make uninstall
./configure --prefix=/usr
make
sudo make install
```
The `make uninstall` is here to cleanup the previous installation.

Then resync the sysroot on your ubuntu vm and try again ;)

**Comment by claussteinmassl** [comment]
Hey!

Please excuse my late answer. Daily business stopped me from further investigating this issue.
I think I totally messed up something, since I got even errors when trying to uninstall libgphoto on the pi. So I decided to start from scratch with a clean installation of Raspbian Jessie on the pi and a fresh installation of my virtual machine with ubuntu.

Unfortunately I end up with the same problem. Here are the steps I did:
-  Install packages on the pi:
`sudo apt-get install libudev-dev libinput-dev libts-dev libxcb-xinerama0-dev htop
sudo apt-get install libltdl-dev
sudo apt-get install libexif-dev
sudo apt-get install libturbojpeg1-dev
sudo apt-get install libusb-dev
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install gdb-multiarch
sudo apt-get install xkb-data console-data
sudo apt-get install gphoto2`
- also installed libgphoto2-6 and libgphoto2-dev on the pi
- sync sysroot to vm
- fix symlinks
- install qt5 on vm
- install qt websockets
- sync qt5pi back to pi
- update dependencies in qhttp
- try to run make

When I run make I get the errors concerning gp_camera_get_single_config and gp_camera_set_single_config again.

I tried to run auoreconf in the vendor/libgphoto2/ dir, but this gives me again the error where it says:
stdarg.h: present but cannot be compiled

I'm really confused what I'm missing now. There can't be an outdated version of libgphoto2, since I only installed the latest one.

**Comment by rlamarche** [comment]
Ok so the libgphoto2 package you installed on the pi is too old.
So you need to compile libgphoto2 yourself. I think that it is easier to do it on the PI.

**Comment by rlamarche** [comment]
You need at least libgphoto 2.5.10

**Comment by claussteinmassl** [comment]
Ok, I:
- ran `sudo apt-get remove libgphoto2-6 libgphoto2-dev` on the pi to remove the old versions,
- cloned the libgphoto2 from Github,
- compiled it and installed it on the pi (with --prefix=/usr as you mentioned),
- rsync everything back to my vm.

If if look into /usr/lib/libgphoto2 (on my pi and the sysroot on my vm) there is version 2.5.12.1 as I would expect.
If I run make, I get the error again (undefined reference to gp_camera_get_single_config etc.). :/

Thanks so much for your patience!

**Comment by rlamarche** [comment]
have you ran `sudo make install` on the PI after the build finished ?

**Comment by rlamarche** [comment]
when you run `make` on your ubuntu, are you sure that you're using the PI Sysroot ?

Which `qmake` command have you ran ?

You should use qmake from the one you builded for your PI.

**Comment by rlamarche** [comment]
`undefined reference` means that the headers are fine, but the libgphoto libs are too old (or there is many versions of the lib).

**Comment by claussteinmassl** [comment]
My qmake command is this: `~/raspi/qt5/bin/qmake`
So if I'm not mistaking something, I use the one builded for my pi (I followed all the instructions here: [https://wiki.qt.io/RaspberryPi2EGLFS](url).

To be honest, I'm not sure, if I'm correctly using the PI sysroot.
I followed the instructions here: [https://github.com/rlamarche/camera-toolbox#compile](url)
So I ignored the optional part about libgphoto since I already installed in on my pi and did the rest exactly as stated. So what I did is:

> # Required
> git submodule init
git submodule update
>
> # Required
> cd vendor/qhttp
./update-dependencies.sh
cd ../../
>
>~/raspi/qt5/bin/qmake
make

Since in '/usr/lib/libgphoto2' (on my pi and the sysroot on my vm) there is only version 2.5.12.1, I don't understand where I should look for another (old) version of the lib.

**Comment by rlamarche** [comment]
Can you run `find -name "libgphoto2.so"` in your /usr and your sysroot ?
Post the results here
Thanks

**Comment by claussteinmassl** [comment]
Ok, these are my results:

Result from pi:
`./lib/libgphoto2.so`

Result from sysroot:
`./lib/libgphoto2.so
./lib/arm-linux-gnueabihf/libgphoto2.so`

I guess, the second one in the sysroot maybe shouldn't be there?

Thank you!

**Comment by rlamarche** [comment]
ok interesting, you have a libgphoto in the arm-linux.. folder, this not normal.
can you diff it with the one in ./lib ?

**Comment by claussteinmassl** [comment]
Running `diff ./lib/libgphoto2.so ./lib/arm-linux-gnueabihf/libgphoto2.so` gives me:
`Binary files ./lib/libgphoto2.so and ./lib/arm-linux-gnueabihf/libgphoto2.so differ`

If I run `cmp ./lib/libgphoto2.so ./lib/arm-linux-gnueabihf/libgphoto2.so`, it gives me:
`./lib/libgphoto2.so ./lib/arm-linux-gnueabihf/libgphoto2.so differ: byte 25, line 1`

May the file in the arm-linux-dir come from running this command?
`CFLAGS="--sysroot /path/to/sysroot" PATH="$PATH:/path/to/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/" ./configure --host=arm-linux-gnueabihf`

I tried this some time ago in the vendor/libgphoto2 directory as stated in your instructions before you marked it as optional.

**Comment by rlamarche** [comment]
ok so remove the oldest libgphoto2.so file (based on the file date).
or remove the two and rerun the rsync.

**Comment by claussteinmassl** [comment]
I just noticed that in `/sysroot/usr/lib/arm-linux-gnueabihf/libgphoto2` there is version 2.5.4!
Should I remove everything related to libgphoto in `/sysroot/usr/lib/arm-linux-gnueabihf/`?

![bildschirmfoto 2017-02-20 um 15 25 03](https://cloud.githubusercontent.com/assets/25461697/23128899/dcb73bd4-f780-11e6-8397-cec5443a7dc6.png)

**Comment by rlamarche** [comment]
yes ! :)

**Comment by claussteinmassl** [comment]
Great! That worked! Thank you so much for your patience! :)

So now I would create a folder 'pi' in the home-dir of my vm, run `make install` and rsync folders from home/pi back to the raspberry, right?

**Comment by rlamarche** [comment]
Well very good news :+1: 
Now the target path for install is /usr/local/bin so don't run `make install` however it will go in your local machine /usr/local/bin (ubuntu).

If the compilation succeeded, look for the binary `camera-toolbox`, copy it on the PI and run it. Put it wherever you want ;)

**Comment by rlamarche** [comment]
Run with command :
```
QT_QPA_EGLFS_FORCE888=1 ./camera-toolbox
```

This prevent low color mode for EGLFS.
What kind of camera do you have ?

**Comment by claussteinmassl** [comment]
Ok, just be sure I get it right: The binary is the one in 'camera-toolbox/app/camera-toolbox'? :)

I will try as soon as I'm home, since I don't have physical access to my pi right now. I'm really excited to try everything! :)

I've got a Canon 400D and a Canon 6D.
I think the 400D is quite outdated, and won't support the liveview, but the 6D should do.
I've also got access to my girlfriends camera, which is a Nikon. But I don't know the exact model name right now, need to check this later.

**Comment by rlamarche** [comment]
Yes this is this one : `camera-toolbox/app/camera-toolbox`

I hope that it will work fine. The other guy that tested on a canon camera don't get the liveview but the camera is very old (Canon Rebel XT).

On Nikon Camera it has been successfully tested on D800 & D600. It should work starting with the D5000.
The D3XXX series won't have liveview support.

**Comment by claussteinmassl** [comment]
Ok, I'm crossing fingers! :)

I will report asap. Should I open a new Issue for everything related to that or should I keep posting to this thread?

**Comment by rlamarche** [comment]
No I think that this issue is resolved, you can close it ;)

**Comment by claussteinmassl** [comment]
ok! 👍
